### ISSUE TITLE
Programmatic selection of child widgets?

### ISSUE THREAD

**Issue by jdickey** [ageweke/fortitude#30]
Let's say I have a `FullNavbar` widget, that needs to display one of multiple `Menu::Whatever` widgets based on conditions determined outside itself that it *shouldn't* have any reason to be privy to. "Fine," I think, "I'll just assign a widget *class* to a `menu_adder` `needs` variable (change in strategy); the `Navbar` will at some point have the line `widget menu_adder`, and all will be fine and dandy. A five-minute job."

"A five-minute job" as in SS *Minnow*'s ["three-hour tour"](http://ssminnow.ca/), apparently...

The error as reported by MiniTest::Spec running my specs, along with the first lines of stack dump down to my `widget` code, are

```
Widgets::Page::FullNavbar::renders markup via the #to_html method that::by default::has a wrapper element::contains a Bootstrap container that::contains a "navbar-collapse" :div which::contains a "navbar-collapse" :div that::contains a :ul element that#test_0001_has the correct CSS classes:
RuntimeError: can't modify frozen #<Class:#<Class:0x007fe5363a77a8>>
    /path/to/the_app/vendor/ruby/2.2.0/gems/fortitude-0.9.4/lib/fortitude/widget/needs.rb:60:in `needs_as_hash'
    /path/to/the_app/vendor/ruby/2.2.0/gems/fortitude-0.9.4/lib/fortitude/widget/needs.rb:127:in `rebuild_my_needs_methods!'
    /path/to/the_app/vendor/ruby/2.2.0/gems/fortitude-0.9.4/lib/fortitude/widget/needs.rb:116:in `block in ensure_needs_methods_are_valid!'
    /path/to/the_app/vendor/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in `instrument'
    /path/to/the_app/vendor/ruby/2.2.0/gems/fortitude-0.9.4/lib/fortitude/widget/integration.rb:14:in `rebuilding'
    /path/to/the_app/vendor/ruby/2.2.0/gems/fortitude-0.9.4/lib/fortitude/widget/needs.rb:115:in `ensure_needs_methods_are_valid!'
    (eval):2:in `assign_locals_from'
    /path/to/the_app/vendor/ruby/2.2.0/gems/fortitude-0.9.4/lib/fortitude/widget/rendering.rb:85:in `initialize'
    /path/to/the_app/vendor/ruby/2.2.0/gems/fortitude-0.9.4/lib/fortitude/widget/rendering.rb:58:in `new'
    /path/to/the_app/vendor/ruby/2.2.0/gems/fortitude-0.9.4/lib/fortitude/widget/rendering.rb:58:in `widget'
    /path/to/the_app/app/views/page/full_navbar.rb:57:in `block in navbar_menu'
```

The mentioned line 57 is the `widget` call in

```ruby
module Widgets
  module Page
    class FullNavbar < Views::Base
      needs menu_adder

      # ...

      def navbar_menu
        ul(class: 'nav navbar-nav') do
          widget menu_adder
        end # ul
      end
    end # class
  end
end
```

Any ideas on how to go about tackling this sort of thing? Or should I go back to my original plan and pass in a lambda for `menu_adder` rather than a widget?

**Comment by jdickey** [comment]
I think I had this solved a while ago and forgot to close the issue. Sorry about that.

**Comment by ageweke** [comment]
@jdickey — thanks for reporting this! I know you closed it because you'd solved the issue, but I'm trying to be very careful to clean up any and all Fortitude bugs, and want to make sure I understand what was going on here.

The issue seems to be that something called [`#freeze`](http://ruby-doc.org/core-2.2.3/Object.html#method-i-freeze) on the `Class` that you passed in (the one assigned to `menu_adder`). Fortitude does lazy initialization of some data it needs on widget classes — in this case, a `Hash` of the class's `needs` variables — and stores it as an `@` variable on the `Class`. If the `Class` is frozen, that blows up.

Did you ever figure out why and how that class was frozen? If it's Fortitude, or even if it's a very common framework that `#freeze`s view classes, I'd be interested in seeing if I can work around it somehow…

  Thanks!
   Andrew

**Comment by ageweke** [comment]
I'm going to close this — I haven't seen this elsewhere, and calling `#freeze` on a `Class` is both an unusual thing to do and, in a general sense, not really safe: many libraries may depend on modifying a `Class` at runtime. (This is Ruby, not Java. ;) )

If you run into this again or know what caused this, and it’s something standard (or, god forbid, Fortitude itself) rather than an edge case, by all means, let me know, and I’ll fix right away!
