### ISSUE TITLE
Unit testing of widgets without loading entire Rails stack in test environment?

### ISSUE THREAD

**Issue by jdickey** [ageweke/fortitude#31]
(Largely a conceptual variation on #28)

Is it possible to test rendering of widgets from "fast Ruby" tests that don't load the entire Rails environment, or is (what I assume to be) the `ActionView` dependency dependent on enough outside Rails "magic" to be pulled out by itself reasonably? Has anyone successfully accomplished this?

**Comment by ageweke** [comment]
Hey! I'm back! Completed the PCT a few days ago, and can get back to working on Fortitude.

As far as I'm aware, Fortitude is not dependent on `ActionView` or anything else from Rails. The only dependencies that [`fortitude.gemspec`](https://github.com/ageweke/fortitude/blob/master/fortitude.gemspec) declares are as follows:

```ruby
  s.add_dependency "activesupport", *activesupport_spec
  s.add_dependency "ref", ">= 1.0.5"
```

Basically, it's just `ActiveSupport` and [`ref`](https://github.com/ruby-concurrency/ref).

In fact, the vast majority of Fortitude's own specs are written this way — everything in [`spec/system`](https://github.com/ageweke/fortitude/tree/master/spec/system), which tests all of Fortitude's core functionality. And these run really, really fast as a result (2.88 seconds for 549 examples, on my machine). The stuff in [`spec/rails`](https://github.com/ageweke/fortitude/tree/master/spec/rails) does depend on Rails, but that's all done via booting up an out-of-process Rails server (via my [`oop_rails_server`](https://github.com/ageweke/oop_rails_server) gem), and shouldn't add any dependencies to Fortitude at all.

Fortitude does _recognize_ Rails, if it's present, and add hooks allowing it to be used seamlessly with Rails ([`lib/fortitude/rails.rb`](https://github.com/ageweke/fortitude/blob/master/lib/fortitude/rails.rb)), but that also shouldn't add any dependencies. What behavior are you seeing? I certainly want to keep Fortitude independent of Rails — it should work seamlessly with Rails if you're using it, but should never require it nor prevent you from writing really fast tests. :)

**Comment by ageweke** [comment]
Again, I think the comment in #34 should be helpful here. In short, it’s completely and totally possible to test Fortitude widgets without Rails being loaded (or even available) in the least — you can just `.new.to_html` them, and it will all “just work”. 

Now, if those widgets depend on Rails features, helpers, or variables in order to render themselves, then, yes, the short version is that you _do_ have to have Rails loaded, and have to get the right integration going so the widget is rendered against the proper Rails `view_context`. If this doesn’t “just work” in any environment in which other rendering engines “just work”, let me know, and I’ll fix it right away.
