### ISSUE TITLE
Script to convert to and from HTML/ERb?

### ISSUE THREAD

**Issue by croaky** [ageweke/fortitude#32]
Howdy! I looked in the codebase and didn't see one, so apologies if it already exists, but is there a CLI to convert Fortitude files to HTML and vice-versa? Something like https://github.com/erector/erector/blob/master/lib/erector/erect/erect.rb#L118-L148 In the context of a Rails app in particular.

**Comment by jdickey** [comment]
@croaky Have you seen [`html2fortitude`](https://github.com/ageweke/html2fortitude)? ISTR it needs a little cleanup, but I was able to get that working for a one-off conversion a couple of months ago.

That bit in [`Erector::Erect#to_html`](https://github.com/erector/erector/blob/master/lib/erector/erect/erect.rb#L118-L148) looks Useful; I've been futzing around with `rails console`, instantiating and calling `#to_html` on my own widgets manually, but that won't fly for everything (*cough* Rails action views *cough*). Thanks for pointing that out.

@ageweke, I haven't stumbled across anything that maps directly to what he's asking for on the Fortitude-to-HTML side; have I missed something or would bringing up a quick `fortitude2html` project based on that [Erector code](https://github.com/erector/erector/blob/master/lib/erector/erect/erect.rb#L118-L148) be worthwhile?

**Comment by croaky** [comment]
Nice, thanks! I hadn't seen `html2fortitude` so thanks for pointing it out.

**Comment by ageweke** [comment]
@croaky, sorry that `html2fortitude` isn’t documented yet! As I push forward on Fortitude, that’s on my (long!) list of things to document.

@jdickey and @croaky, I’m not sure how a general-purpose `.html.rb` —> `.html` converter would work. If widgets have no `needs` and don’t use any helpers that require access to data, then, sure, it wouldn’t be too hard…but my gut says that this likely isn’t a common case — since, if what you have is effectively static HTML, why not just write it as static HTML in the first place?

(I recognize the irony in this, in that I’m writing Fortitude’s docs exactly as Fortitude widgets that create static HTML. They’re getting built using [Middleman](https://middlemanapp.com/), which can also be seen as a tool that does exactly that: bulk conversion of `.html.rb` (and `.html.erb`, and so on) to HTML, in a controlled manner.)

If you have a specific, reasonably-common use case in mind for `.html.rb` —> `.html`, I’d be more than happy to give it a shot — I’m just not sure enough exactly what that is yet in order to feel like I could do a good job on it.

Thanks!
Andrew
