### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by Gaelan** [ageweke/fortitude#46]
What is the status of this project? Is it still being worked on?

**Comment by jdickey** [comment]
(**NOTE:** I am not (yet) a maintainer, nor do I play one on TV.)

As of about 5-6 months ago, development was fairly active; Andrew (@ageweke) had just returned from his PCT trek, and was responding to at least some (e.g., my) issue comments.

I *presume* he got diverted again by his day job, as did I (I've been doing API work since about then, and haven't touched Rails with malice aforethought during that time. (Though he *did* respond to you on #25, if that slipped through the cracks?)

Andrew, as you've noticed, people have made several forks since 42dc90d and the issues *are* getting rather long in the tooth; if you're still buried, maybe it's time to think about a co-maintainer, or at least, say, a "road map" issue discussion thread with your ideas of where the hottest fires are? I *should* be able to start poking at stuff regularly again from mid-july, if I can help.

**Comment by Gaelan** [comment]
Yeah, I need to respond on #25. :) I saw the response, didn’t get around to responding back, and forgot about it. I’ll try and get a response in today. I don’t think I’m experienced enough to be a good co-maintainer, but I’d be quite happy if this project go going again.

**Comment by harlantwood** [comment]
+1 for a co-maintainer.  maybe @alexch might be interested?  Just volunteering you Alex 😄

**Comment by ajb** [comment]
Hey there -- @vlymar and I are working on some maintenance (and a Rails 5 update) as our company uses Fortitude pretty heavily.

I'd like to volunteer for maintainer duty, if Andrew is around to grant it.

**Comment by karlhe** [comment]
He was previously very active and has been completely silent since around April, I can only assume something is preventing him from being able to maintain the project.

Maybe at this point there should be an agreed upon fork until he returns?

**Comment by ageweke** [comment]
Hi!

(pausing as everyone’s shocked to see me)

My apologies for disappearing like that. I had a combination of a long vacation (hiking the PCT), followed by some significant chaos in my personal life, followed by a pretty intense job. However…I just left said job, and now have more time to work on Fortitude again. And I’m going to try to keep that up now.

It looks like there’s some truly excellent work that’s been happening in my absence, and I’m going to take a look at that stuff ASAP — I’m starting by getting the Travis build fixed, but then I’m going to look at the branches, PRs, and bugs everyone has filed and start working through them.

Many thanks to everyone who’s chipped in during my absence, and my apologies for said absence. I’m looking forward to bringing this all back together again!

Andrew

**Comment by ajb** [comment]
Welcome back! 🎉

**Comment by ageweke** [comment]
I’m closing this…status should now be clear, and every PR and issue I can see has been fixed for 0.9.5, which I just released. :) I still plan to write docs now that I have some time to do it, but I think Fortitude’s in much better shape now!
