### ISSUE TITLE
Regression: automatic inclusion of Rails helpers breaks implicit route arguments

### ISSUE THREAD

**Issue by ajb** [ageweke/fortitude#57]
So I've actually looked for where this is documented in the Rails docs and can't find it, but given a route like this:

<img width="832" alt="screen shot 2016-10-18 at 2 54 53 pm" src="https://cloud.githubusercontent.com/assets/1270317/19497789/d954a40e-9542-11e6-881f-bd913689c50a.png">

And if you have instance variables for `@site` and `@project`, you can call the route explicitly:

```
project_admin_responses_path(@site.id, @project.id)
```

Or you can leave out the arguments, and Rails will implicitly pass your instance variables to the route helper:

```
project_admin_responses_path
```

However, the change in https://github.com/ageweke/fortitude/commit/d7eeec4886ee9a62b52fd0a2a571d82a32bde2b5 (which I don't quite understand in the first place) breaks this second syntax:

<img width="918" alt="screen shot 2016-10-18 at 2 56 15 pm" src="https://cloud.githubusercontent.com/assets/1270317/19497841/0a423a18-9543-11e6-9f8a-56acd41349b8.png">

I think I understand _why_, but I'm wondering if this would be considered a regression, and if this is OK. I find it weird that you had to specify `default_url_options` in https://github.com/ageweke/fortitude/commit/d7eeec4886ee9a62b52fd0a2a571d82a32bde2b5#diff-c039a5faaa76d9264a41ffc542ef3a82R87, since Rails shouldn't need those when rendering views.

Thoughts?

**Comment by ajb** [comment]
Alright, rather than stealthily editing my first post, I'll amend it here:

It looks like I might be misinformed about the instance variables, and it's actually the _current request's parameters_ that are implicitly passed to the path helpers. The issue still stands, though! :D

**Comment by ageweke** [comment]
This definitely is a bug! Got a working test case repro’ing it — let me fix.

**Comment by ajb** [comment]
Sweet, thanks!

**Comment by ageweke** [comment]
OK, all fixed. It’s on a weird branch (`ageweke/rails_generator_support`), but I’ll merge that into master once it’s green on Travis. Fix is [here](https://github.com/ageweke/fortitude/commit/b65f4fcac9504a66e7fa5a12d957b2f73b40fd7a).

Ironically, this issue was caused by exactly some of the stuff we were talking about in the caching thread — `Rails.application.routes.url_helpers` (which is a `Module`) was being `include`'d directly into `Fortitude::Widget`, causing those methods to end up run in the context of the widget (and thus didn’t have access to the incoming request), rather than on that magic/special helpers object that Rails creates, where they belong.

**Comment by ajb** [comment]
Awesome, thanks for the quick turnaround!

**Comment by ajb** [comment]
If you get a chance, it would be great to have this on Rubygems :)
