### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by ajb** [ageweke/fortitude#9]
I wrote this [caching module](https://github.com/ajb/erector-rails4/blob/master/lib/erector/caching.rb) for erector-rails4, which adds all of the neat cache_digests stuff to widgets. What's even cooler about using cache_digests in Erector is that because your needs are explicit, you can calculate the `cache_key` for a widget without having to manually specify the objects it depends on. 

Is this something you'd be interested in implementing in fortitude? Anything about the implementation that you'd want to change?

**Comment by jdickey** [comment]
Hey, @ageweke, just came across `static` and kicking myself for not reading this issue sooner. :smile_cat: 

One question: we have something of a shop standard (for classes in general) that methods that are mutually ignorant of object state get put into an `Internals` module as class methods. For instance, this is close to one of our actual page widgets:

```ruby

require_relative 'index_content' # declares Views::Welcome::Index::Content class
require 'menu_factory'

# Class encapsulating all page-specific view code for `welcome/index`.
class Views::Welcome::Index < Views::Base
  # Methods neither dependent on nor affecting instance state.
  module Internals
    def self.menu_factory
      MenuFactory.new
        .add_item(href: '#', caption: 'Home')
        .add_separator
        .add_item(href: '#', caption: 'Sign up')
        .add_item(href: '#', caption: 'Sign in')
    end
  end
  private_constant :Internals

  def content
    widget Views::Page, page_content: Content, nav_menu: Internals.menu_factory
  end
end # class Views::Welcome::Index
```

(For those wondering, we do this to silence [Reek](https://github.com/troessner/reek) complaints about methods that don't affect instance state, that simply declaring `def self.menu_factory` in the outer class won't kill.)

How *does* Fortitude see this class? Will it treat the `Internals` module (and thus `.menu_factory`) as something it can automagically treat as `static`? Am I confusing the hell out of someone or something? And what's "best practice" here as far as Fortitude is concerned?

**Comment by ageweke** [comment]
@jdickey — first off, don't worry about feeling like a n00b! Fortitude still has effectively no documentation (which I'm working on), and so it's just impressive that folks are able to use it at all. Feel free to ask away…anything at all. I'm more than happy to answer any questions!

A brief introduction to `static`: `static` is a performance improvement for Fortitude when rendering large amounts of purely static HTML — _i.e._, HTML that is independent of any server or user data. For example, if you have a "typical" footer for a site that has links to the FAQ, About, Facebook, Twitter, and so on, probably none of that data ever changes. The code thus might look something a little like this:

```ruby
  def footer
    div {
      ul {
        li { a("Facebook", :href => "http://www.facebook.com/…") }
        li { a("Twitter", :href => "http://www.twitter.com/…") }
        …
      }
      …
    }
  end
```

Because Fortitude works like it does, every single time any page is rendered, it's going to invoke every method — `div`, `ul`, `li`, `a`, etc. — in that footer, generating that same identical HTML. 

This is inefficient — it's the exact same string every time, so why are we doing all this work? If you add `static :footer` above, here's what Fortitude does:

* The first time `#footer` is called, anywhere in your application, Fortitude runs the method. However, when it does so, it (a) prohibits any access to any `needs` variables (since the whole idea here is to speed up HTML that never changes), and (b) saves the output of that method.
* Next, it replaces the original `#footer` method on that class with one that simply splats out that same output.

In essence, once it's run the first time, that method now becomes:

```ruby
  def footer
    rawtext "<div><ul><li><a href="http://www.facebook.com/…">Facebook</a></li><li><a href="http://www.twitter.com/…">Twitter</a></li>…"
  end
```

This runs much faster than the method above, because it's a single string concatenation, rather than a bunch of nested methods with blocks.

One of the reasons that I've placed documenting `static` lower on the list than some other things is that I think it's very rarely necessary. My (own, real-world-esque benchmarks)[https://github.com/ageweke/rails_view_benchmarks] show Fortitude _without_ any use of `static` whatsoever as being 20% faster than ERb, 3x faster than HAML, and a whopping 29x faster than Erector. Slim is 8% faster than Fortitude without `static`, but, with `static`, Fortitude is about 28% faster than Slim. Fortitude generates a ~375KByte page of complex, real-world HTML in about 32ms without `static`, and about 22ms with `static`.

(An interesting point: most other templating engines are fastest when cranking out large chunks of static HTML — because, to them, it's just giant strings to be concatenated directly onto the output — and slowest when doing lots of interpolation, `if` statements, and so on. Fortitude is exactly the opposite, which I feel good about. If you have lots of static HTML, speeding it up is usually very easy (there are tons of technologies, in and out of Rails, for doing so), and it's not really where Rails shines, either. But if you have lots of dynamic HTML, partials, conditionals, sub-views, etc. that depend on data from your server, _that_ is where Rails shines, and that's where Fortitude shines, too.)

My guess is that for most applications, this difference is going to be in the noise until they've spent lots of time optimizing elsewhere. So I'd encourage folks to ignore `static` completely until they get deep into the optimization phase and find that squeezing an extra 5–10ms out of their views becomes important to them. But it's there when you need it, and can be valuable.

Coming back to your example: without seeing the code for `MenuFactory`, I can't tell if `Internals.menu_factory` returns some object that exposes methods that `Views::Page` would call on it (_i.e._, "return the list of menu items"), or if simply calling `Internals.menu_factory` actually renders HTML itself. If it's the former, there's no point in even trying to make it `static`, because `static` only applies to methods that render HTML. If it's the latter: you can't make a method `static` unless it's an instance method of a widget itself, since only those will have access to tag methods (`p`, `div`, etc.). 

Is it the latter? If so, it's an interesting question you pose. I can definitely see the value in the convention you describe (and I love it when Rubyists think like this), but also don't see an immediate solution. I'll think more on it, though, if that's what you're trying to do. Is it?

  Cheers,
    Andrew

**Comment by jdickey** [comment]
@ageweke Thanks for the wondrously informative reply! I've a much clearer understanding of `static` now, and I don't find your benchmarks/comparisons wrt other templating engines surprising at all. 

For the record, the code in `Internals.menu_factory` just loads up an internal data structure (a list of entries, if you will) that a call to [`MenuFactory#widget`](https://github.com/jdickey/new_fortstrap/blob/master/lib/menu_factory.rb#L13-L15) (from [within](https://github.com/jdickey/new_fortstrap/blob/master/app/views/page.rb#L49) `Views::Page`) then uses to render a widget. It's (quite probably) overly ceremonious, but it got the job done while the bulk of the development of the three widgets involved took place at different times and assumptions.

Fortitude is already turning into Great Stuff for us; documentation would be an Amazingly Good Thing,, of course, and in a few weeks I'm going to have to sit down and figure out how to put several of these widgets (the standard-page-layout widgets discussed here among them) into Gems we can decouple maintenance of from the apps that use them. I put a week into trying to wrap my head around that while you were enjoying your hike and gave up; hopefully I'll have better success next time.

Thanks again!

**Comment by ageweke** [comment]
I’m gonna close this for now — it’d be great to fold discussion in under PR #54. :)
